Fix the attachment to the container
There is no --tmpfs option for `podman container exec` because we are
attaching to an existing container.

  Error: unknown flag: --tmpfs
  See 'podman container exec --help'
  make: *** [/home/me/devkit/devkit.mk:305: run] Error 125

Fixes: ddbc4eb ("Mount /run and /tmp as tmpfs")
Signed-off-by: Alexey Gladkov <gladkov.alexey@gmail.com>